apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-odh-oauth2
  namespace: istio-system
data:
  token-secret.yaml: |-
    resources:
    - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
      name: token
      generic_secret:
        secret:
          inline_string: "${CLIENT_SECRET}"
  hmac-secret.yaml: |-
    resources:
    - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
      name: hmac
      generic_secret:
        secret:
          inline_bytes: "${CLIENT_HMAC}"