apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auth-delegator.clusterrolebinding.yaml
  - cluster-monitoring-role-binding.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - role.yaml
  - role-binding.yaml
  